class SkillCategory {
  final String emoji;
  final String name;
  final List<String> skills;

  const SkillCategory({
    required this.emoji,
    required this.name,
    required this.skills,
  });
}

const List<SkillCategory> skillCategories = [
  SkillCategory(
    emoji: '💻',
    name: 'Technology',
    skills: [
      'Python',
      'JavaScript',
      'React',
      'Flutter',
      'Swift',
      'Kotlin',
      'Rust',
      'Go',
      'TypeScript',
      'Node.js',
      'Docker',
      'AWS',
      'Machine Learning',
      'Data Science',
      'Cybersecurity',
      'Blockchain',
      'DevOps',
      'SQL',
    ],
  ),
  SkillCategory(
    emoji: '🎨',
    name: 'Design & Creative',
    skills: [
      'UI/UX Design',
      'Figma',
      'Graphic Design',
      'Motion Graphics',
      'Illustration',
      'Photography',
      'Video Editing',
      'Brand Identity',
      '3D Modeling',
      'Animation',
      'Procreate',
      'Adobe Suite',
    ],
  ),
  SkillCategory(
    emoji: '📈',
    name: 'Business',
    skills: [
      'Marketing',
      'SEO',
      'Copywriting',
      'Sales',
      'Product Management',
      'Financial Analysis',
      'Entrepreneurship',
      'Public Speaking',
      'Negotiation',
      'Leadership',
      'Project Management',
      'Business Strategy',
    ],
  ),
  SkillCategory(
    emoji: '🗣️',
    name: 'Languages',
    skills: [
      'English',
      'Spanish',
      'French',
      'Mandarin',
      'Arabic',
      'German',
      'Japanese',
      'Korean',
      'Portuguese',
      'Italian',
      'Hindi',
      'Russian',
    ],
  ),
  SkillCategory(
    emoji: '🎵',
    name: 'Music & Audio',
    skills: [
      'Guitar',
      'Piano',
      'Singing',
      'Music Production',
      'DJ-ing',
      'Songwriting',
      'Sound Design',
      'Mixing & Mastering',
      'Drums',
      'Violin',
    ],
  ),
  SkillCategory(
    emoji: '🍳',
    name: 'Culinary',
    skills: [
      'Cooking',
      'Baking',
      'Meal Prep',
      'Sushi Making',
      'Pastry',
      'Fermentation',
      'Cocktail Making',
      'Food Styling',
      'Nutrition',
      'BBQ & Grilling',
    ],
  ),
  SkillCategory(
    emoji: '💪',
    name: 'Fitness & Wellness',
    skills: [
      'Yoga',
      'Weight Training',
      'Meditation',
      'Running',
      'Calisthenics',
      'Martial Arts',
      'Swimming',
      'Dance',
      'Pilates',
      'Nutrition Planning',
    ],
  ),
  SkillCategory(
    emoji: '✍️',
    name: 'Writing & Content',
    skills: [
      'Content Writing',
      'Technical Writing',
      'Blogging',
      'Screenwriting',
      'Poetry',
      'Journalism',
      'Podcast Production',
      'Storytelling',
      'Editing',
      'Grant Writing',
    ],
  ),
];
